# Generated by Django 4.2.30 on 2026-05-25 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=120)),
                ('source_type', models.CharField(max_length=80)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_filename', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('source_details', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='dataapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=80)),
                ('source_name', models.CharField(max_length=120)),
                ('source_row_id', models.CharField(blank=True, max_length=255)),
                ('source_raw', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('commodity', models.CharField(blank=True, max_length=120)),
                ('location_code', models.CharField(blank=True, max_length=120)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('quantity_value', models.FloatField(blank=True, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=40)),
                ('normalized_quantity', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=40)),
                ('activity_value', models.FloatField(blank=True, null=True)),
                ('activity_unit', models.CharField(blank=True, max_length=40)),
                ('emission_kg_co2e', models.FloatField(blank=True, null=True)),
                ('cost_usd', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('flagged_reasons', models.JSONField(blank=True, default=list)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='dataapp.importbatch')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dataapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='dataapp.emissionrecord')),
            ],
        ),
    ]
